kramdown:
  footnote_backlink: '&#8617;&#65038;'

plugins:
  - jekyll-seo-tag



baseurl: "/new.peril.lol"
title: Nicholas Jaffer
tagline: Student & Dev-In-Training
description: Portfolio and more of Amanda Pinsker, independent product & experience designer.
Author: Amanda Pinsker
image: "/img/og-img.png"
lang: en_US
twitter:
  username: ampinsk
  card: summary
